# Generated by Django 5.2.4 on 2025-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="accounts/profile_pictures/default.jpg",
                upload_to="accounts/profile_pictures/",
            ),
        ),
    ]
