services:
  web:
    build: .
    container_name: e_commerce_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./core/.env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./core/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.5-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=e_commerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4471hamed
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.0-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - static_data:/app/static
      - media_data:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data: