# Generated by Django 5.2.4 on 2025-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="media/products/default.jpg", upload_to="media/products"
            ),
        ),
    ]
