# Generated by Django 5.2.4 on 2025-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
    ]
