# Generated by Django 5.2.4 on 2025-07-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("stores", "0002_alter_store_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="store",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="stores.store",
            ),
        ),
    ]
