# Generated by Django 5.2.4 on 2025-07-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "در انتظار پرداخت"), (2, "موفق"), (3, "ناموفق")],
                        default=1,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("card_pan", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
