# Generated by Django 5.2.4 on 2025-07-23 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="seller",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
